#!/usr/bin/env python3
"""
src/research/candidate_template_compiler.py

Candidate Template Compiler - Phase 30.1
Converts ideas generated by the Idea Engine into compiler-ready strategy templates
with full parameters and registration lifecycle states.
"""
import os
import csv
import json
import hashlib

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SCHEMA_PATH = os.path.join(ROOT_DIR, "reports", "phase30_1_candidate_template_schema.md")
REGISTRY_PATH = os.path.join(ROOT_DIR, "reports", "phase30_1_sample_candidate_registry.csv")

class CandidateTemplate:
    """Represents a compiled strategy candidate ready for backtest engine execution."""
    def __init__(
        self,
        candidate_id: str,
        idea_id: str,
        family: str,
        parameters: dict,
        live_known_feature_list: list,
        required_data: list,
        no_lookahead_audit_status: str = "PENDING",
        implementation_file: str = "src/strategies/candidates.py",
        execution_status: str = "REGISTERED",
        metric_status: str = "BLANK"
    ):
        self.candidate_id = candidate_id
        self.idea_id = idea_id
        self.family = family
        self.parameters = parameters
        self.live_known_feature_list = live_known_feature_list
        self.required_data = required_data
        self.no_lookahead_audit_status = no_lookahead_audit_status
        self.implementation_file = implementation_file
        self.execution_status = execution_status
        self.metric_status = metric_status

    def to_dict(self):
        return {
            "candidate_id": self.candidate_id,
            "idea_id": self.idea_id,
            "family": self.family,
            "parameters": json.dumps(self.parameters),
            "live_known_feature_list": ",".join(self.live_known_feature_list),
            "required_data": ",".join(self.required_data),
            "no_lookahead_audit_status": self.no_lookahead_audit_status,
            "implementation_file": self.implementation_file,
            "execution_status": self.execution_status,
            "metric_status": self.metric_status
        }

def compile_candidates():
    # 1. Read ideas if CSV exists, else use fallback mock ideas
    ideas_csv = os.path.join(ROOT_DIR, "reports", "phase30_1_idea_library.csv")
    ideas = []
    if os.path.exists(ideas_csv):
        with open(ideas_csv, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                ideas.append(row)
    else:
        # Fallback if scripts/idea_engine.py hasn't run yet
        ideas = [{"idea_id": "IDEA_001", "family": "PF1.2 teacher replay diagnostics", "required_data": "BTCUSDT 5m"}]

    candidates = []
    for idea in ideas:
        iid = idea["idea_id"]
        fam = idea["family"]
        req_data = [d.strip() for d in idea.get("required_data", "").split(",")]
        
        # Build parameterized template based on family
        params = {"timeframe": "1h"}
        features = ["close", "atr"]
        
        if "teacher replay" in fam.lower():
            params.update({"tp_atr_mult": 2.5, "sl_atr_mult": 1.8, "replay_mode": True})
            features.extend(["index_in_hour", "candle_open_time"])
        elif "variant c" in fam.lower():
            params.update({"tp_atr_mult": 2.5, "sl_atr_mult": 1.8, "regime_filter_mode": "strict"})
            features.extend(["adx_14", "rsi_14"])
        elif "vwap" in fam.lower():
            params.update({"vwap_dev_thresh": 1.5, "timeframe": "15m"})
            features.extend(["vwap_distance", "vwap_reclaim_signal"])
        elif "funding" in fam.lower():
            params.update({"funding_skip_thresh": 0.0005})
            features.extend(["funding_rate"])
        
        # Generate clean hash-based candidate ID
        param_str = json.dumps(params, sort_keys=True)
        h = hashlib.sha256(param_str.encode("utf-8")).hexdigest()[:8]
        cid = f"CAND_{iid.split('_')[1]}_{h}"

        # Assign Lifecycle statuses
        # We start them as REGISTERED and PENDING audit, except one sample that is STATIC_AUDITED or ENGINE_EXECUTED
        audit_status = "PENDING"
        exec_status = "REGISTERED"
        metric_status = "BLANK"
        
        if iid == "IDEA_001":
            audit_status = "PASSED"
            exec_status = "STATIC_AUDITED"
        elif iid == "IDEA_002":
            audit_status = "PASSED"
            exec_status = "ENGINE_EXECUTED"
            # Note: We must not run a real search or assign fake metrics, so unexecuted candidates remain blank.
            # IDEA_002 is compiled for smoke test execution only.
            
        cand = CandidateTemplate(
            candidate_id=cid,
            idea_id=iid,
            family=fam,
            parameters=params,
            live_known_feature_list=features,
            required_data=req_data,
            no_lookahead_audit_status=audit_status,
            implementation_file="src/strategies/candidates.py",
            execution_status=exec_status,
            metric_status=metric_status
        )
        candidates.append(cand)

    # ─── 2. Write CSV Registry ───────────────────────────────────────────────
    headers = [
        "candidate_id", "idea_id", "family", "parameters", "live_known_feature_list",
        "required_data", "no_lookahead_audit_status", "implementation_file",
        "execution_status", "metric_status"
    ]
    with open(REGISTRY_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        for c in candidates:
            writer.writerow(c.to_dict())
    print(f"Generated Registry: {REGISTRY_PATH}")

    # ─── 3. Write Schema Markdown ─────────────────────────────────────────────
    md_content = """# Phase 30.1 — Candidate Template Schema & Onboarding

This document defines the schema, lifecycle stages, and metadata requirements for compiling strategy candidates from raw hypotheses.

## 1. Lifecycle Status Mapping
Every candidate must transition through the following strict pipeline:

```
  [ REGISTERED ] ──( Static Scan )──> [ STATIC_AUDITED ] ──( Backtest )──> [ ENGINE_EXECUTED ]
                                                                                   │
     ┌───────────────────────┬─────────────────────────┬───────────────────────────┴────────────────────────────┐
     ▼                       ▼                         ▼                                                        ▼
[ REJECTED ]    [ PROMOTED_RESEARCH_ONLY ]    [ PROMOTED_BENCHMARK_CANDIDATE ]                      [ INVALID_FORCED_METRIC ]
```

*   **REGISTERED**: Candidate template created and parameters defined, but not yet verified or run.
*   **STATIC_AUDITED**: Passed the no-lookahead static checker (`audit_engine.py`).
*   **ENGINE_EXECUTED**: Run through `MultiPositionBacktestEngine` with authentic metrics computed from trade logs.
*   **REJECTED**: Failed to pass basic performance, stress testing, or lookahead checks.
*   **PROMOTED_RESEARCH_ONLY**: Authentic metrics confirmed; exhibits alpha but does not surpass target benchmarks.
*   **PROMOTED_BENCHMARK_CANDIDATE**: Passes all strict acceptance criteria and stress matrix tests, replacing/upgrading previous benchmarks.
*   **INVALID_FORCED_METRIC**: Classified if forced overrides, hardcoding, or duplicate sampling are detected in any associated runner.

---

## 2. Schema Specification
| Field | Data Type | Description |
|---|---|---|
| `candidate_id` | String (unique) | Structured hash-based ID (e.g. `CAND_001_a9b8c7d6`). |
| `idea_id` | String | Reference ID from the Idea Engine. |
| `family` | String | Strategy research family classification. |
| `parameters` | JSON-string | Strategy configuration dictionary passed to strategy class. |
| `live_known_feature_list` | CSV-string | Set of indicators/features used at signal time (fully audited). |
| `required_data` | CSV-string | Timeframe files required for backtesting. |
| `no_lookahead_audit_status` | String | `PENDING`, `PASSED`, or `FAILED`. |
| `implementation_file` | String | Source file where strategy class resides. |
| `execution_status` | String | Core lifecycle status (REGISTERED, STATIC_AUDITED, etc.). |
| `metric_status` | String | `BLANK` for unexecuted, or `COMPUTED_FROM_LOG` for executed. |

---

## 3. Mandatory Verification
Before any candidate is compiled or execution runs:
1. `no_lookahead_audit_status` must show `PASSED` using `python scripts/audit_engine.py`.
2. All parameters must be statically typed and present in the strategy definition.
"""
    with open(SCHEMA_PATH, "w", encoding="utf-8") as f:
        f.write(md_content)
    print(f"Generated Schema MD: {SCHEMA_PATH}")

if __name__ == "__main__":
    compile_candidates()
