#!/usr/bin/env python3
"""
scripts/idea_engine.py

Generates 15 structured strategy hypotheses representing the key research families
needed to solve the core Precision Fusion trading problems.
Outputs:
  - reports/phase30_1_idea_library.csv
  - reports/phase30_1_top_ideas.md
"""
import os
import csv
import sys

# Define target output paths
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
CSV_PATH = os.path.join(ROOT_DIR, "reports", "phase30_1_idea_library.csv")
MD_PATH = os.path.join(ROOT_DIR, "reports", "phase30_1_top_ideas.md")

# Predefined structured ideas with 24 requested fields
STRUCTURED_IDEAS = [
    {
        "idea_id": "IDEA_001",
        "family": "PF1.2 teacher replay diagnostics",
        "name": "Teacher Trade Replay & Path Verification",
        "hypothesis": "Replaying original 325 teacher trades at 5m resolution isolates candle-structure assumptions from physical price execution.",
        "target_problem": "PF1.2 5m engine trade log mismatch (3,111 trades, PF 0.64).",
        "target_benchmark": "PF 1.2",
        "expected_live_known_features": "candle_open_time, index_in_hour, close_to_atr_ratio",
        "required_timeframe": "5m",
        "entry_logic": "Execute entry at the exact timestamp recorded in the 1h teacher log.",
        "exit_logic": "Simulate stop-loss (1.8x ATR) and take-profit (2.5x ATR) using 5m high/low paths.",
        "risk_logic": "Conservative stop-first same-candle resolution.",
        "why_it_might_work": "Accurately maps which teacher trades are stopped out before target, validating the engine path.",
        "why_it_might_fail": "If teacher entries were based on hindsight indices not present in live data.",
        "lookahead_risk": "None (replay is diagnostic only).",
        "hardcoding_risk": "High if used directly for live trading; low if used as a diagnostic.",
        "overfit_risk": "Low (no parameter fitting).",
        "expected_trade_count_impact": "Reduces test trades to exactly 325 matching candidate times.",
        "expected_pf_impact": "Identifies true realizable PF of the teacher set.",
        "expected_dd_impact": "Reveals the true physical drawdown path.",
        "required_data": "BTCUSDT 5m OHLCV, phase12_runner.py trade logs",
        "implementation_complexity": "Medium",
        "test_priority": "High (Priority 1)",
        "kill_criteria": "If 100% of trades are instantly stopped out due to data alignment gaps.",
        "success_criteria": "Accurate tracking of every teacher trade survival status with path logs."
    },
    {
        "idea_id": "IDEA_002",
        "family": "Variant C live rebuild",
        "name": "Strict Regime Breakout Live Compiler",
        "hypothesis": "Compiling Variant C with strict closed-candle regime gates prevents entry in choppy periods.",
        "target_problem": "Variant C decay under event-driven 5m backtests.",
        "target_benchmark": "Variant C",
        "expected_live_known_features": "adx_14, rsi_14, closed_regime_index",
        "required_timeframe": "1h",
        "entry_logic": "Universal template breakout only when ADX > 25 and RSI is neutral.",
        "exit_logic": "Fixed ATR stop and target based on closed-candle values at entry time.",
        "risk_logic": "Single position limit, cooldown of 5 candles.",
        "why_it_might_work": "Enforces 1h candle rules strictly without intra-candle lookahead.",
        "why_it_might_fail": "May reduce trade count below statistical significance.",
        "lookahead_risk": "None if using strictly closed 1h candles.",
        "hardcoding_risk": "None (fully dynamic).",
        "overfit_risk": "Medium (regime thresholds).",
        "expected_trade_count_impact": "Reduces trades by 30-40% compared to un-gated.",
        "expected_pf_impact": "Improves PF by filtering low-volatility false breakouts.",
        "expected_dd_impact": "Reduces max DD by preventing whipsaws.",
        "required_data": "BTCUSDT 1h processed OHLCV",
        "implementation_complexity": "Medium",
        "test_priority": "High",
        "kill_criteria": "If net PnL becomes negative over the full 2020-2026 backtest.",
        "success_criteria": "reproduces Variant C targets without using any lookahead metrics."
    },
    {
        "idea_id": "IDEA_003",
        "family": "Variant B rescue rebuild",
        "name": "Variant B Broad-Capture Recovery",
        "hypothesis": "Variant B's looser breakout filters can be rescued by adding a dynamic volume confirmation filter.",
        "target_problem": "Variant B low profit factor (1.92) compared to PF 1.2.",
        "target_benchmark": "Variant B",
        "expected_live_known_features": "volume_ratio, breakout_conviction",
        "required_timeframe": "1h",
        "entry_logic": "Breakout entry when volume is at least 1.5x the 20-period moving average.",
        "exit_logic": "ATR trailing exit or 2.0x ATR profit target.",
        "risk_logic": "Risk throttle mode based on recent 30-day drawdown.",
        "why_it_might_work": "Volume filters out low-participation breakout signals.",
        "why_it_might_fail": "Binance volume spikes are frequently mean-reverting.",
        "lookahead_risk": "None (uses closed-candle volume).",
        "hardcoding_risk": "None.",
        "overfit_risk": "Medium.",
        "expected_trade_count_impact": "Reduces trades by 20% but increases average win size.",
        "expected_pf_impact": "Increases PF from 1.92 to 2.10+.",
        "expected_dd_impact": "Maintains DD below 12.0%.",
        "required_data": "BTCUSDT 1h processed OHLCV + volume",
        "implementation_complexity": "Medium",
        "test_priority": "Medium",
        "kill_criteria": "If trade count drops below 200.",
        "success_criteria": "Net PnL > $18,000 and PF > 2.0."
    },
    {
        "idea_id": "IDEA_004",
        "family": "MTF retest confirmation",
        "name": "Multi-Timeframe Breakout Confirmation",
        "hypothesis": "Requiring a 5m wick retest confirmation of a 1h breakout level improves entry precision.",
        "target_problem": "High slippage and execution decay of 1h breakout entries.",
        "target_benchmark": "PF 1.2",
        "expected_live_known_features": "is_1h_breakout, has_5m_retest, distance_to_breakout",
        "required_timeframe": "1h + 5m",
        "entry_logic": "1h candle closes in breakout; entry is placed on limit order at the 1h breakout level during next 1h.",
        "exit_logic": "SL/TP managed at 5m resolution based on 1h ATR.",
        "risk_logic": "Cancel limit order if not filled within 12 5m candles.",
        "why_it_might_work": "Enables limit order execution (maker fees) instead of market orders (taker fees).",
        "why_it_might_fail": "Missing high-momentum breakouts that never retest the level.",
        "lookahead_risk": "Low (1h closes first, then 5m limits are evaluated).",
        "hardcoding_risk": "None.",
        "overfit_risk": "Medium (limit timeout setting).",
        "expected_trade_count_impact": "Reduces trade count by 50% due to unfilled limits.",
        "expected_pf_impact": "Significant increase in PF due to lower fees and better fills.",
        "expected_dd_impact": "Slightly higher risk if missed wins skew the distribution.",
        "required_data": "BTCUSDT 1h + 5m processed data",
        "implementation_complexity": "High",
        "test_priority": "High",
        "kill_criteria": "If match rate with teacher trades falls below 10%.",
        "success_criteria": "Maker entry execution with positive PnL in backtest."
    },
    {
        "idea_id": "IDEA_005",
        "family": "VWAP reclaim",
        "name": "VWAP Band Reclaim Strategy",
        "hypothesis": "Entering when price reclaims the daily VWAP after a deviation filters out exhaustive trends.",
        "target_problem": "False breakout entries at the extreme ends of range regimes.",
        "target_benchmark": "PF 1.2",
        "expected_live_known_features": "vwap_distance, vwap_reclaim_signal",
        "required_timeframe": "15m",
        "entry_logic": "Price crosses daily VWAP from below (long) or above (short) after deviating by 1.5x ATR.",
        "exit_logic": "Exit at opposite VWAP band or 2.0x ATR.",
        "risk_logic": "Hard stop at 1.5x ATR from entry.",
        "why_it_might_work": "Exploits intraday mean-reversion with positive expectation.",
        "why_it_might_fail": "During strong trending regimes, price does not reclaim VWAP.",
        "lookahead_risk": "None (uses closed VWAP value).",
        "hardcoding_risk": "None.",
        "overfit_risk": "Low.",
        "expected_trade_count_impact": "Provides 150-200 high-quality range trades.",
        "expected_pf_impact": "Maintains PF > 2.0 in range markets.",
        "expected_dd_impact": "Low correlation with trend strategies reduces combined DD.",
        "required_data": "BTCUSDT 15m processed OHLCV + VWAP",
        "implementation_complexity": "Medium",
        "test_priority": "Medium",
        "kill_criteria": "If PF in trending months is less than 0.8.",
        "success_criteria": "Range regime PF > 2.2."
    },
    {
        "idea_id": "IDEA_006",
        "family": "second retest",
        "name": "Double Retest Confirmation Filter",
        "hypothesis": "Wait for two tests of a support/resistance level on the 5m chart before entering a reversal.",
        "target_problem": "Catching falling knives on single-wick rejections.",
        "target_benchmark": "Variant B",
        "expected_live_known_features": "retest_count, wick_rejection_ratio",
        "required_timeframe": "5m",
        "entry_logic": "Enter after the second 5m candle wick rejects a major hourly level.",
        "exit_logic": "Target at next hourly resistance/support.",
        "risk_logic": "Tight stop just below the lowest wick price.",
        "why_it_might_work": "Higher conviction setup due to confirmed support/resistance.",
        "why_it_might_fail": "Misses fast V-shape reversals.",
        "lookahead_risk": "None.",
        "hardcoding_risk": "None.",
        "overfit_risk": "Medium (wick detection tolerance).",
        "expected_trade_count_impact": "Low frequency (30-50 trades over full history).",
        "expected_pf_impact": "Very high PF (> 2.50) on successful setups.",
        "expected_dd_impact": "Minimal DD impact due to very tight stops.",
        "required_data": "BTCUSDT 5m processed OHLCV",
        "implementation_complexity": "Medium",
        "test_priority": "Low",
        "kill_criteria": "If trade frequency is less than 5 trades per year.",
        "success_criteria": "Win rate > 60% on completed trades."
    },
    {
        "idea_id": "IDEA_007",
        "family": "funding defensive skip",
        "name": "Extreme Funding Defensive Skip",
        "hypothesis": "Skipping long entries when funding rate is extremely positive (or shorts when negative) prevents carrying toxic holding costs.",
        "target_problem": "PnL erosion due to negative funding payments in high-leverage positions.",
        "target_benchmark": "PF 1.2",
        "expected_live_known_features": "funding_rate, funding_cost_est",
        "required_timeframe": "1h",
        "entry_logic": "Skip any long entry if funding rate > 0.05% per 8 hours.",
        "exit_logic": "No change to standard target/stop exits.",
        "risk_logic": "Proactively limits carry risk.",
        "why_it_might_work": "Avoids entering crowded trades right before funding settlement epochs.",
        "why_it_might_fail": "May skip high-momentum breakout trades that outweigh funding costs.",
        "lookahead_risk": "None (uses pre-settlement funding rates).",
        "hardcoding_risk": "None.",
        "overfit_risk": "Low (funding threshold is standard exchange limit).",
        "expected_trade_count_impact": "Reduces trades by 5-10% in bubble market regimes.",
        "expected_pf_impact": "Increases PF by saving margin costs.",
        "expected_dd_impact": "Reduces drawdown in extended consolidation periods.",
        "required_data": "Binance BTCUSDT funding rate history",
        "implementation_complexity": "Low",
        "test_priority": "High",
        "kill_criteria": "If total net PnL decreases after applying the filter.",
        "success_criteria": "Saves at least $1,000 in cumulative funding rate costs."
    },
    {
        "idea_id": "IDEA_008",
        "family": "NY low-liquidity hardening",
        "name": "New York Session Liquidity Filter",
        "hypothesis": "Restricting breakout entries to high-volume hours (London/NY overlap) reduces low-liquidity false breaks.",
        "target_problem": "False breakouts during Asian session and NY afternoon market thinness.",
        "target_benchmark": "PF 1.2",
        "expected_live_known_features": "market_hour, volume_zscore",
        "required_timeframe": "1h",
        "entry_logic": "Only enter breakouts between 07:00 and 16:00 UTC.",
        "exit_logic": "Standard exits; time-based exit if held > 24 hours.",
        "risk_logic": "No same-candle modifications.",
        "why_it_might_work": "Enforces trading when institutional volume is highest.",
        "why_it_might_fail": "Crypto is a 24/7 market; major moves frequently start in Asia.",
        "lookahead_risk": "None (uses current timestamp).",
        "hardcoding_risk": "Low (hour parameters are standard market segments).",
        "overfit_risk": "Low.",
        "expected_trade_count_impact": "Reduces trades by 40-50%.",
        "expected_pf_impact": "Increases PF significantly during breakout runs.",
        "expected_dd_impact": "Prevents weekend/holiday price whipsaws.",
        "required_data": "BTCUSDT 1h processed OHLCV with hour index",
        "implementation_complexity": "Low",
        "test_priority": "Medium",
        "kill_criteria": "If it filters out the top 5 most profitable trades of the strategy.",
        "success_criteria": "Reduces false breakouts by at least 25%."
    },
    {
        "idea_id": "IDEA_009",
        "family": "weak continuation exits",
        "name": "Weak Momentum Early Exit",
        "hypothesis": "Exiting a trade early if momentum (ADX/RSI) fails to accelerate within 3 candles reduces average loss.",
        "target_problem": "Extended flat periods before a stop loss is eventually hit.",
        "target_benchmark": "Variant C",
        "expected_live_known_features": "candles_since_entry, adx_slope, rsi_flatline",
        "required_timeframe": "1h",
        "entry_logic": "No change to standard entry.",
        "exit_logic": "Exit at market close if trade is not in profit and ADX slope < 0 after 3 candles.",
        "risk_logic": "Protects capital by freeing margin for better setups.",
        "why_it_might_work": "Minimizes time spent in slow, flat, or sideways markets.",
        "why_it_might_fail": "Might cut profitable trades short before the move starts.",
        "lookahead_risk": "None (uses elapsed candles).",
        "hardcoding_risk": "None.",
        "overfit_risk": "Medium (candle window length parameter).",
        "expected_trade_count_impact": "No impact on entry count; decreases average holding time.",
        "expected_pf_impact": "Slight improvement in PF.",
        "expected_dd_impact": "Reduces drawdown by preventing slow bleed outs.",
        "required_data": "BTCUSDT 1h processed OHLCV",
        "implementation_complexity": "Medium",
        "test_priority": "Medium",
        "kill_criteria": "If win rate drops below 35%.",
        "success_criteria": "Reduces average holding time of losing trades by 30%."
    },
    {
        "idea_id": "IDEA_010",
        "family": "breakeven/trailing/time-stop",
        "name": "Dynamic Breakeven & Time Exit",
        "hypothesis": "Moving stop-loss to breakeven after price reaches 1.0x ATR profit protects open equity.",
        "target_problem": "Winning trades turning into complete losers due to quick market reversals.",
        "target_benchmark": "PF 1.2",
        "expected_live_known_features": "max_unrealized_pnl, atr_at_entry",
        "required_timeframe": "5m",
        "entry_logic": "No change to entry.",
        "exit_logic": "Adjust SL to entry price once unrealized PnL exceeds 1.0x ATR. Add 48-candle hard time limit.",
        "risk_logic": "Non-overlapping stop order modifications.",
        "why_it_might_work": "Locks in protection and prevents capital drag from stagnant positions.",
        "why_it_might_fail": "Prematurely stops out trades that retest the entry level before moving to target.",
        "lookahead_risk": "None.",
        "hardcoding_risk": "None.",
        "overfit_risk": "Medium (ATR threshold setting).",
        "expected_trade_count_impact": "Increases number of flat trades (PnL = 0).",
        "expected_pf_impact": "Increases PF by reducing gross losses.",
        "expected_dd_impact": "Improves equity curve smoothness.",
        "required_data": "BTCUSDT 5m processed OHLCV",
        "implementation_complexity": "Medium",
        "test_priority": "High",
        "kill_criteria": "If the number of breakeven stopped trades exceeds 60% of all trades.",
        "success_criteria": "Reduces max DD by at least 15% without reducing net PnL by more than 10%."
    },
    {
        "idea_id": "IDEA_011",
        "family": "Dirty PF8 quality surgery",
        "name": "Dirty PF8 Core Cleansing",
        "hypothesis": "Isolating and removing the high-drawdown candidate clusters in the Dirty PF8 set recovers clean strategy growth.",
        "target_problem": "Dirty PF8 drawdown risk (15.29%) and forced PnL delta history.",
        "target_benchmark": "Dirty PF8",
        "expected_live_known_features": "cluster_id, candidate_correlation",
        "required_timeframe": "1h",
        "entry_logic": "Execute only candidates in clusters 1, 2, and 4; reject cluster 3 completely.",
        "exit_logic": "Standard ATR stop and target.",
        "risk_logic": "Portfolio conflict cancellation.",
        "why_it_might_work": "Removes correlated failure paths identified during cluster forensics.",
        "why_it_might_fail": "Remaining clusters might still suffer from underlying market structure shift.",
        "lookahead_risk": "None (uses static cluster definitions).",
        "hardcoding_risk": "Low (offline clustering is diagnostic, execution is static).",
        "overfit_risk": "Medium (selection bias).",
        "expected_trade_count_impact": "Reduces trade count to a clean, non-overlapping ~300 trades.",
        "expected_pf_impact": "Increases PF to > 2.0.",
        "expected_dd_impact": "Reduces DD below 10.0%.",
        "required_data": "phase29_2_dirty_pf8_cluster_report.md, trade logs",
        "implementation_complexity": "Medium",
        "test_priority": "Medium",
        "kill_criteria": "If the reconstructed system fails to reproduce positive metrics.",
        "success_criteria": "reproduces a clean backtest with zero hardcoded delta overrides."
    },
    {
        "idea_id": "IDEA_012",
        "family": "session/liquidity filters",
        "name": "Liquidity Gap Defensive Gate",
        "hypothesis": "Skipping entries when daily volume is below the 10-day moving average prevents slippage during thin markets.",
        "target_problem": "High slippage costs and sudden wicks during holiday or weekend periods.",
        "target_benchmark": "PF 1.2",
        "expected_live_known_features": "rolling_volume_avg, current_daily_volume",
        "required_timeframe": "1h",
        "entry_logic": "Only enter if 24h rolling volume is above the 10-day average volume.",
        "exit_logic": "No change.",
        "risk_logic": "Proactive liquidity check.",
        "why_it_might_work": "Avoids entering trades when market depth is thin.",
        "why_it_might_fail": "May skip high-momentum breakout moves that happen during low-volume weekends.",
        "lookahead_risk": "None (uses rolling historical volume).",
        "hardcoding_risk": "None.",
        "overfit_risk": "Low.",
        "expected_trade_count_impact": "Reduces trades by 15-20%.",
        "expected_pf_impact": "Improves PF by reducing slippage losses.",
        "expected_dd_impact": "Slight reduction in drawdown.",
        "required_data": "BTCUSDT 1h processed OHLCV + volume data",
        "implementation_complexity": "Low",
        "test_priority": "Medium",
        "kill_criteria": "If slippage costs do not decrease in stress testing.",
        "success_criteria": "Slippage-adjusted net PnL improves by at least 8%."
    },
    {
        "idea_id": "IDEA_013",
        "family": "volatility expansion/compression",
        "name": "Bollinger Band Width Squeeze Filter",
        "hypothesis": "Requiring a period of volatility compression (Bollinger Band width < threshold) before entering a breakout increases success rate.",
        "target_problem": "Chop losses caused by entering breakouts during wide, choppy volatility ranges.",
        "target_benchmark": "PF 1.2",
        "expected_live_known_features": "bb_width, rolling_volatility_compression",
        "required_timeframe": "1h",
        "entry_logic": "Only enter breakout if Bollinger Band width was in the lowest 25% of the last 100 candles.",
        "exit_logic": "Standard ATR TP/SL.",
        "risk_logic": "Volatility-based entry gates.",
        "why_it_might_work": "Filters out late trend-continuation entries, catching moves at start of expansion.",
        "why_it_might_fail": "Slow consolidation periods can lead to false breakouts that resolve in opposite directions.",
        "lookahead_risk": "None.",
        "hardcoding_risk": "None.",
        "overfit_risk": "Medium (width percentile threshold).",
        "expected_trade_count_impact": "Reduces trade count by 30-40%.",
        "expected_pf_impact": "Increases PF to > 2.2.",
        "expected_dd_impact": "Reduces drawdowns in sideways markets.",
        "required_data": "BTCUSDT 1h processed data with Bollinger Bands",
        "implementation_complexity": "Medium",
        "test_priority": "High",
        "kill_criteria": "If total net PnL is lower than baseline PF 1.2.",
        "success_criteria": "Breakout win rate increases from 45% to 52%."
    },
    {
        "idea_id": "IDEA_014",
        "family": "expected-R dynamic gates",
        "name": "Dynamic Expected R-Multiple Gate",
        "hypothesis": "Only entering setups when the ratio of average win to average loss in the current regime is > 2.0 optimizes equity curves.",
        "target_problem": "Entering low expected value setups during low-volatility regimes.",
        "target_benchmark": "PF 1.2",
        "expected_live_known_features": "regime_expected_r, rolling_win_loss_ratio",
        "required_timeframe": "1h",
        "entry_logic": "Only enter trade if (TP distance / SL distance) based on current ATR exceeds 2.0.",
        "exit_logic": "No change.",
        "risk_logic": "Dynamic reward-to-risk gate.",
        "why_it_might_work": "Enforces a strict positive expectancy filter on every position.",
        "why_it_might_fail": "High-expectancy trades might have lower win rates, skewing the distribution.",
        "lookahead_risk": "None.",
        "hardcoding_risk": "None.",
        "overfit_risk": "Low.",
        "expected_trade_count_impact": "Filters out low-reward setups (reduces count by 10-15%).",
        "expected_pf_impact": "Slightly improves PF.",
        "expected_dd_impact": "Reduces drawdowns in low-volatility environments.",
        "required_data": "BTCUSDT 1h processed OHLCV",
        "implementation_complexity": "Low",
        "test_priority": "Medium",
        "kill_criteria": "If win rate drops below 30%.",
        "success_criteria": "Average trade win size increases by 15%."
    },
    {
        "idea_id": "IDEA_015",
        "family": "cross-asset generalization",
        "name": "Cross-Asset Volatility Porting",
        "hypothesis": "A strategy template calibrated on BTC should generalize to ETH, BNB, and SOL if adjusted for asset-specific volatility.",
        "target_problem": "Strategy failure and overfit when running on non-BTC assets.",
        "target_benchmark": "PF 1.2",
        "expected_live_known_features": "asset_relative_volatility, normalize_atr",
        "required_timeframe": "1h",
        "entry_logic": "Use BTC template rules, but scale ATR stops and targets dynamically based on the target asset's relative volatility to BTC.",
        "exit_logic": "Scaled stops and targets.",
        "risk_logic": "Asset-specific risk allocation sizing.",
        "why_it_might_work": "Maintains structural logic while adapting to higher/lower beta profiles.",
        "why_it_might_fail": "Assets like SOL and BNB have distinct regime cycles and funding behaviors from BTC.",
        "lookahead_risk": "None.",
        "hardcoding_risk": "None.",
        "overfit_risk": "Low.",
        "expected_trade_count_impact": "Expands trade count dramatically across the portfolio.",
        "expected_pf_impact": "Maintains positive PF across all 4 assets.",
        "expected_dd_impact": "Diversifies risk, flattening the combined portfolio DD.",
        "required_data": "ETH, BNB, SOL 1h processed OHLCV",
        "implementation_complexity": "High",
        "test_priority": "Medium",
        "kill_criteria": "If any non-BTC asset produces a negative PnL over the full period.",
        "success_criteria": "Positive PnL on all 4 assets with a combined PF > 1.8."
    }
]

def generate_library():
    """Generates the CSV file and the Markdown report."""
    os.makedirs(os.path.join(ROOT_DIR, "reports"), exist_ok=True)

    # ─── 1. Write CSV ────────────────────────────────────────────────────────
    headers = [
        "idea_id", "family", "name", "hypothesis", "target_problem", "target_benchmark",
        "expected_live_known_features", "required_timeframe", "entry_logic", "exit_logic",
        "risk_logic", "why_it_might_work", "why_it_might_fail", "lookahead_risk",
        "hardcoding_risk", "overfit_risk", "expected_trade_count_impact", "expected_pf_impact",
        "expected_dd_impact", "required_data", "implementation_complexity", "test_priority",
        "kill_criteria", "success_criteria"
    ]
    with open(CSV_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        writer.writerows(STRUCTURED_IDEAS)
    print(f"Generated CSV: {CSV_PATH}")

    # ─── 2. Write Markdown ───────────────────────────────────────────────────
    md_content = [
        "# Phase 30.1 — Reusable Research Idea Library",
        "\nThis library contains 15 structured strategy hypotheses representing the key research families required to address Precision Fusion goals.",
        "\n## Summary of Families",
        "The following families are mapped out with all 24 required audit and logic parameters:",
        ""
    ]
    for idx, idea in enumerate(STRUCTURED_IDEAS, 1):
        md_content.append(f"{idx}. **{idea['idea_id']}**: {idea['name']} ({idea['family']})")

    md_content.extend([
        "\n## Top Ranked Ideas",
        "\n### 1. IDEA_001 — Teacher Trade Replay & Path Verification",
        f"- **Family:** {STRUCTURED_IDEAS[0]['family']}",
        f"- **Hypothesis:** {STRUCTURED_IDEAS[0]['hypothesis']}",
        f"- **Target Problem:** {STRUCTURED_IDEAS[0]['target_problem']}",
        f"- **Expected Live-Known Features:** `{STRUCTURED_IDEAS[0]['expected_live_known_features']}`",
        f"- **Required Data:** {STRUCTURED_IDEAS[0]['required_data']}",
        f"- **Entry/Exit:** {STRUCTURED_IDEAS[0]['entry_logic']} / {STRUCTURED_IDEAS[0]['exit_logic']}",
        f"- **Complexity / Priority:** {STRUCTURED_IDEAS[0]['implementation_complexity']} / {STRUCTURED_IDEAS[0]['test_priority']}",
        f"- **Why it might work / fail:** {STRUCTURED_IDEAS[0]['why_it_might_work']} / {STRUCTURED_IDEAS[0]['why_it_might_fail']}",
        f"- **Lookahead / Hardcoding Risk:** {STRUCTURED_IDEAS[0]['lookahead_risk']} / {STRUCTURED_IDEAS[0]['hardcoding_risk']}",
        f"- **Success / Kill Criteria:** {STRUCTURED_IDEAS[0]['success_criteria']} / {STRUCTURED_IDEAS[0]['kill_criteria']}",

        "\n### 2. IDEA_004 — Multi-Timeframe Breakout Confirmation",
        f"- **Family:** {STRUCTURED_IDEAS[3]['family']}",
        f"- **Hypothesis:** {STRUCTURED_IDEAS[3]['hypothesis']}",
        f"- **Target Problem:** {STRUCTURED_IDEAS[3]['target_problem']}",
        f"- **Expected Live-Known Features:** `{STRUCTURED_IDEAS[3]['expected_live_known_features']}`",
        f"- **Required Data:** {STRUCTURED_IDEAS[3]['required_data']}",
        f"- **Entry/Exit:** {STRUCTURED_IDEAS[3]['entry_logic']} / {STRUCTURED_IDEAS[3]['exit_logic']}",
        f"- **Complexity / Priority:** {STRUCTURED_IDEAS[3]['implementation_complexity']} / {STRUCTURED_IDEAS[3]['test_priority']}",
        f"- **Why it might work / fail:** {STRUCTURED_IDEAS[3]['why_it_might_work']} / {STRUCTURED_IDEAS[3]['why_it_might_fail']}",
        f"- **Lookahead / Hardcoding Risk:** {STRUCTURED_IDEAS[3]['lookahead_risk']} / {STRUCTURED_IDEAS[3]['hardcoding_risk']}",
        f"- **Success / Kill Criteria:** {STRUCTURED_IDEAS[3]['success_criteria']} / {STRUCTURED_IDEAS[3]['kill_criteria']}",

        "\n### 3. IDEA_010 — Dynamic Breakeven & Time Exit",
        f"- **Family:** {STRUCTURED_IDEAS[9]['family']}",
        f"- **Hypothesis:** {STRUCTURED_IDEAS[9]['hypothesis']}",
        f"- **Target Problem:** {STRUCTURED_IDEAS[9]['target_problem']}",
        f"- **Expected Live-Known Features:** `{STRUCTURED_IDEAS[9]['expected_live_known_features']}`",
        f"- **Required Data:** {STRUCTURED_IDEAS[9]['required_data']}",
        f"- **Entry/Exit:** {STRUCTURED_IDEAS[9]['entry_logic']} / {STRUCTURED_IDEAS[9]['exit_logic']}",
        f"- **Complexity / Priority:** {STRUCTURED_IDEAS[9]['implementation_complexity']} / {STRUCTURED_IDEAS[9]['test_priority']}",
        f"- **Why it might work / fail:** {STRUCTURED_IDEAS[9]['why_it_might_work']} / {STRUCTURED_IDEAS[9]['why_it_might_fail']}",
        f"- **Lookahead / Hardcoding Risk:** {STRUCTURED_IDEAS[9]['lookahead_risk']} / {STRUCTURED_IDEAS[9]['hardcoding_risk']}",
        f"- **Success / Kill Criteria:** {STRUCTURED_IDEAS[9]['success_criteria']} / {STRUCTURED_IDEAS[9]['kill_criteria']}",
        
        "\n### 4. IDEA_013 — Bollinger Band Width Squeeze Filter",
        f"- **Family:** {STRUCTURED_IDEAS[12]['family']}",
        f"- **Hypothesis:** {STRUCTURED_IDEAS[12]['hypothesis']}",
        f"- **Target Problem:** {STRUCTURED_IDEAS[12]['target_problem']}",
        f"- **Expected Live-Known Features:** `{STRUCTURED_IDEAS[12]['expected_live_known_features']}`",
        f"- **Required Data:** {STRUCTURED_IDEAS[12]['required_data']}",
        f"- **Entry/Exit:** {STRUCTURED_IDEAS[12]['entry_logic']} / {STRUCTURED_IDEAS[12]['exit_logic']}",
        f"- **Complexity / Priority:** {STRUCTURED_IDEAS[12]['implementation_complexity']} / {STRUCTURED_IDEAS[12]['test_priority']}",
        f"- **Why it might work / fail:** {STRUCTURED_IDEAS[12]['why_it_might_work']} / {STRUCTURED_IDEAS[12]['why_it_might_fail']}",
        f"- **Lookahead / Hardcoding Risk:** {STRUCTURED_IDEAS[12]['lookahead_risk']} / {STRUCTURED_IDEAS[12]['hardcoding_risk']}",
        f"- **Success / Kill Criteria:** {STRUCTURED_IDEAS[12]['success_criteria']} / {STRUCTURED_IDEAS[12]['kill_criteria']}",
    ])

    with open(MD_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(md_content))
    print(f"Generated MD: {MD_PATH}")

if __name__ == "__main__":
    generate_library()
